# Intelligent News Aggregator - User Preferences (Phase 1)
# Version: 0.1.0 (Simplified for Phase 1)
# Last Updated: October 23, 2025

# ========================================
# TOPICS (Phase 1: Only 2 topics)
# ========================================

topics:
  # 1. AI & Machine Learning (Highest Priority)
  - name: "AI & Machine Learning"
    keywords:
      - "artificial intelligence"
      - "machine learning"
      - "LLM"
      - "large language model"
      - "GPT"
      - "Claude"
      - "neural network"
      - "deep learning"
      - "transformer"
      - "AI research"
      - "foundation models"
    exclude_keywords:
      - "crypto"
      - "cryptocurrency"
      - "blockchain"
      - "NFT"
      - "web3"
      - "bitcoin"
    priority: 10
    min_articles: 2
    max_articles: 4

  # 2. Science Breakthroughs
  - name: "Science Breakthroughs"
    keywords:
      - "physics breakthrough"
      - "biology discovery"
      - "chemistry"
      - "quantum"
      - "particle physics"
      - "neuroscience"
      - "genetics"
      - "CRISPR"
      - "scientific discovery"
      - "peer-reviewed"
    exclude_keywords:
      - "pseudoscience"
      - "astrology"
    priority: 9
    min_articles: 1
    max_articles: 4

# ========================================
# SOURCES (Phase 1: Only 3 sources)
# ========================================

sources:
  # Tier 1: Premium sources - always include if relevant
  tier1_premium:
    - "arxiv.org"
    - "news.ycombinator.com"
    - "arstechnica.com"

  # Blocklist - never include
  blocklist: []

  # Require verification for all claims
  require_verification: false  # Disabled in Phase 1

  # Cross-reference controversial claims across 2+ sources
  cross_reference_threshold: 2

# ========================================
# OUTPUT PREFERENCES
# ========================================

output:
  # Writing style
  style: "hn_comment_style"  # Technical, skeptical, implications-focused

  # Format
  format: "markdown"

  # Article limits (quality threshold, not fixed count)
  min_articles: 5   # Minimum articles per digest
  max_articles: 12  # Maximum articles per digest

  # Target reading time
  reading_time_target_minutes: 10

  # Content options (simplified for Phase 1)
  include_summaries: true
  include_bias_notes: false      # Phase 3
  include_alternative_perspectives: false  # Phase 3
  include_cross_story_connections: false   # Phase 3
  include_hn_discussion_summary: false     # Phase 2
  include_cost_metadata: true

# ========================================
# QUALITY THRESHOLDS (Simplified for Phase 1)
# ========================================

quality:
  # Base thresholds (no adaptive adjustment in Phase 1)
  min_relevance_score: 0.5   # Lower for Phase 1
  min_quality_score: 0.5     # Lower for Phase 1

  # Adaptive thresholds
  adaptive_threshold: false   # Disabled in Phase 1

# ========================================
# SCHEDULE
# ========================================

schedule:
  frequency: "daily"
  time: "06:00"
  timezone: "America/New_York"

# ========================================
# FEEDBACK & LEARNING (All disabled in Phase 1)
# ========================================

feedback:
  track_file_access: false
  track_reading_time: false
  enable_ratings: false
  enable_favorites: false
  enable_learning: false

# ========================================
# COST BUDGET
# ========================================

budget:
  daily_target_usd: 0.30      # Lower target for Phase 1
  daily_alert_threshold_usd: 0.50
  weekly_alert_threshold_usd: 2.50
  monthly_cap_usd: 15.00
  prefer_cost_optimization: false

# ========================================
# DATA RETENTION (Simplified for Phase 1)
# ========================================

data_retention:
  keep_digests_forever: true
  article_retention_days: 7     # Shorter for Phase 1
  keep_metadata_forever: false  # Disabled in Phase 1
  auto_cleanup_enabled: false   # Disabled in Phase 1

# ========================================
# ADVANCED OPTIONS (Simplified for Phase 1)
# ========================================

advanced:
  # Parallelization (conservative for Phase 1)
  max_parallel_searches: 2
  max_parallel_parsers: 5

  # Error handling
  retry_failed_fetches: true
  max_retries: 2

  # Caching (disabled in Phase 1)
  cache_search_results_hours: 0
  cache_article_content_hours: 0
